FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY prisma ./prisma
COPY tsconfig.json ./
CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npx prisma db seed"]
